version: "3.9"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "9001:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app_monolith
      - db_monolith
      - node
    networks:
      - laravel

  app_monolith:
    container_name: app_monolith
    build:
      context: .
      target: php
      args:
        APP_ENV: ${APP_ENV}
    environment:
      APP_ENV: ${APP_ENV}
      CONTAINER_ROLE: app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    depends_on:
      - db_monolith
    networks:
      - laravel
    # command: >
    #   bash -c "sleep 10 && php artisan serve --port=8080 --host=0.0.0.0 --env=.env"

  # Database Server
  db_monolith:
    networks:
      - laravel
    container_name: db_monolith
    restart: unless-stopped
    tty: true
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  # Node Server
  node:
    build:
      context: .
      target: node
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src
      - ./node_modules:/usr/src/node_modules
    working_dir: /usr/src
    command: npm run dev 
    networks:
      - laravel

volumes:
  db-data: ~